# Generated by Django 5.2.17 on 2026-09-11 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import tracker.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("job_url", models.URLField(blank=True, max_length=1000)),
                ("requisition_id", models.CharField(blank=True, max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("gmail", "Gmail"),
                            ("browser", "Browser capture"),
                            ("import", "Imported"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "work_arrangement",
                    models.CharField(
                        choices=[
                            ("onsite", "On-site"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("temporary", "Temporary"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "salary_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("salary_currency", models.CharField(blank=True, max_length=3)),
                (
                    "salary_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hour", "per hour"),
                            ("day", "per day"),
                            ("month", "per month"),
                            ("year", "per year"),
                        ],
                        max_length=10,
                    ),
                ),
                ("application_date", models.DateField(blank=True, null=True)),
                ("closing_date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("saved", "Saved"),
                            ("preparing", "Preparing"),
                            ("applied", "Applied"),
                            ("screening", "Screening"),
                            ("interviewing", "Interviewing"),
                            ("offer", "Offer"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="saved",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("manual_override_fields", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("display_timezone", models.CharField(default="Africa/Cairo", max_length=64)),
                ("gmail_history_days", models.PositiveIntegerField(default=90)),
                ("follow_up_days", models.PositiveIntegerField(default=7)),
                ("ai_model", models.CharField(default="deepseek-flash", max_length=60)),
                (
                    "ai_monthly_ceiling_usd",
                    models.DecimalField(decimal_places=2, default=10, max_digits=8),
                ),
                ("capture_extension_token_hash", models.CharField(blank=True, max_length=128)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "App settings",
            },
        ),
        migrations.CreateModel(
            name="GmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("credential_ref", models.CharField(blank=True, max_length=120)),
                ("history_id", models.CharField(blank=True, max_length=64)),
                (
                    "connection_state",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("needs_reconnect", "Needs reconnect"),
                            ("error", "Error"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="connected",
                        max_length=20,
                    ),
                ),
                ("include_archived", models.BooleanField(default=True)),
                ("history_days", models.PositiveIntegerField(default=90)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("role", models.CharField(blank=True, max_length=200)),
                ("linkedin_url", models.URLField(blank=True, max_length=1000)),
                ("notes", models.TextField(blank=True)),
                (
                    "applications",
                    models.ManyToManyField(
                        blank=True, related_name="contacts", to="tracker.application"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to=tracker.models.document_upload_path)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("cover_letter", "Cover letter"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=200)),
                ("original_filename", models.CharField(blank=True, max_length=300)),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                (
                    "applications",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="tracker.application"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_id", models.CharField(max_length=255)),
                ("thread_id", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("from_address", models.CharField(blank=True, max_length=320)),
                ("to_addresses", models.CharField(blank=True, max_length=500)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("snippet", models.TextField(blank=True)),
                ("body_text", models.TextField(blank=True)),
                ("label_ids", models.JSONField(blank=True, default=list)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                (
                    "process_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("classified", "Classified"),
                            ("ignored", "Ignored"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="tracker.application",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="tracker.gmailaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("application_confirmation", "Application confirmation"),
                            ("acknowledgment", "Acknowledgment"),
                            ("recruiter_contact", "Recruiter contact"),
                            ("assessment", "Assessment"),
                            ("interview_invitation", "Interview invitation"),
                            ("interview_reschedule", "Interview reschedule"),
                            ("interview_cancellation", "Interview cancellation"),
                            ("offer", "Offer"),
                            ("rejection", "Rejection"),
                            ("withdrawal", "Withdrawal"),
                            ("stage_change", "Stage change"),
                            ("note", "Note"),
                            ("document_added", "Document added"),
                            ("custom", "Custom"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("gmail", "Gmail"),
                            ("browser", "Browser capture"),
                            ("import", "Imported"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        choices=[("system", "System"), ("user", "User")],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("is_correction", models.BooleanField(default=False)),
                (
                    "dedupe_key",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tracker.application",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="tracker.email",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("round", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("phone", "Phone screen"),
                            ("video", "Video call"),
                            ("technical", "Technical"),
                            ("onsite", "On-site"),
                            ("hr", "HR / culture"),
                            ("other", "Other"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("participants", models.JSONField(blank=True, default=list)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("meeting_url", models.URLField(blank=True, max_length=1000)),
                ("prep_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No show"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="tracker.application",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_start", "round", "id"],
            },
        ),
        migrations.CreateModel(
            name="PostingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("url", models.URLField(max_length=1000)),
                ("resolved_url", models.URLField(blank=True, max_length=1000)),
                ("source", models.CharField(blank=True, max_length=40)),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("job_identifier", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.JSONField(blank=True, default=dict)),
                ("raw_html", models.TextField(blank=True)),
                (
                    "capture_state",
                    models.CharField(
                        choices=[
                            ("structured", "Structured"),
                            ("text", "Readable text"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("unknown_fields", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="tracker.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="applications", to="tracker.tag"),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("done", "Done"),
                            ("snoozed", "Snoozed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tracker.application",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=60)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("run_after", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["run_after", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "run_after"], name="tracker_wor_status_1b20fb_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(fields=["thread_id"], name="tracker_ema_thread__ee21ef_idx"),
        ),
        migrations.AddConstraint(
            model_name="email",
            constraint=models.UniqueConstraint(
                fields=("account", "message_id"), name="uniq_email_account_message"
            ),
        ),
        migrations.AddConstraint(
            model_name="postingsnapshot",
            constraint=models.UniqueConstraint(
                fields=("application", "version"), name="uniq_snapshot_app_version"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["stage"], name="tracker_app_stage_5a2858_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["company"], name="tracker_app_company_0f8dde_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["application_date"], name="tracker_app_applica_8d18d5_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status", "due_at"], name="tracker_tas_status_95322b_idx"),
        ),
    ]
