# Generated by Django 5.2.17 on 2026-09-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="extracted",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="backfill_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="sync_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unmatched", "No match found"),
                            ("ambiguous", "Ambiguous match"),
                            ("needs_review", "Needs review"),
                            ("conflict", "Conflicts with your correction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("linked", "Linked"),
                            ("created", "Created"),
                            ("ignored", "Ignored"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("suggestion", models.JSONField(blank=True, default=dict)),
                ("candidates", models.JSONField(blank=True, default=list)),
                ("note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_action", models.CharField(blank=True, max_length=40)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_items",
                        to="tracker.email",
                    ),
                ),
                (
                    "resolved_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_items",
                        to="tracker.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("email",), name="uniq_review_email")
                ],
            },
        ),
    ]
