# Generated by Django 5.2.17 on 2026-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_email_extracted_gmailaccount_backfill_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="process_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("review", "In review"),
                    ("classified", "Classified"),
                    ("ignored", "Ignored"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
